---
- name: Set a letter as a statistic
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Display the inputted number
      ansible.builtin.debug:
        msg: The inputted number was {{ input_number | default('N/A') }}

    - name: Set variable
      ansible.builtin.set_stats:
        per_host: false # not supported by Controller
        data:
          stat_letter: "{{ ['a', 'b'] | random }}"
