---
- name: Tasks by IOS version
  hosts: cisco
  gather_facts: true

  tasks:
    - name: Tasks for 16.xx.xx
      include_tasks: config_16.yml
      when:
        - ansible_net_version is version('16.00.00', '>')
        - ansible_net_version is version('17.00.00', '<')

    - name: Tasks for 17.xx.xx
      include_tasks: config_17.yml
      when:
        - ansible_net_version is version('17.00.00', '>')
        - ansible_net_version is version('18.00.00', '<')
