---
- name: Apply PoE setting to a specific interface
  hosts: ios
  gather_facts: false

  vars:
    interface: GigabitEthernet0/1
    power_setting: auto

  tasks:
    - name: Apply setting
      cisco.ios.ios_config:
        lines: power inline {{ power_setting }}
        parents:
          - interface {{ interface }}
