---
- name: Take and store a network backup
  hosts: cisco,arista
  gather_facts: false

  vars:
    backup_root: /backup

  tasks:
    - name: Run local setup
      ansible.builtin.setup:
      delegate_to: localhost

    - name: Create Network Backup
      ansible.builtin.include_role:
        name: network.backup.backup
      vars:
        type: full
        data_store:
          local:
            path: /tmp
            filename: "{{ inventory_hostname }}.txt"

    - name: Ensure persistent detination exists
      ansible.builtin.file:
        path: "{{ backup_root }}/{{ ansible_date_time.date }}"
        state: directory
        owner: "{{ hostvars['ansible-1']['ansible_user'] }}"
      become: true
      delegate_to: ansible-1

    - name: Copy to persistent destination
      ansible.builtin.copy:
        src: /tmp/{{ inventory_hostname }}.txt
        dest: "{{ backup_root }}/{{ ansible_date_time.date }}/{{ inventory_hostname }}.txt"
        mode: "644"
      delegate_to: ansible-1
